name: Python Application Test

on:
  workflow_dispatch:
    
jobs:
  # build-and-test:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./entryTracker
  #   steps:
  #   # 1. Check out the repository code
  #   - name: Checkout code
  #     uses: actions/checkout@v6
    
  #   # 2. Set up Python 3.10
  #   - name: Set up Python 3.10
  #     uses: actions/setup-python@v5
  #     with:
  #       python-version: '3.10'

  #   # 3. Install requirements
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  #   # 4. Start the application and test with curl
  #   - name: Run App and Test with Curl
  #     run: |
  #       python app.py &
        
  #       sleep 3
        
  #       curl -f http://127.0.0.1:5000/
    
  package-and-e2e:
    # needs: ["build-and-test"]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 1. Set up Docker Buildx (Required for advanced caching features)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 2. Build the Docker image utilizing GitHub Actions Cache
    - name: Build and Package with Cache
      uses: docker/build-push-action@v6
      with:
        context: ./entryTracker
        file: ./entryTracker/Dockerfile
        tags: entry-tracker:latest
        load: true # This loads the image into the local Docker daemon so compose can use it
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: List images
      run: docker images  

    # 3. Spin up the containers (They will now successfully read the job-level Env vars)
    - name: Prepare for e2e test
      run: |
        printenv | grep "DB"
        docker compose up -d
      env:
        DB_HOST: ${{ vars.DB_HOST }} 
        DB_USER: ${{ vars.DB_USER }}
        DB_NAME: ${{ vars.DB_NAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
   
    # 4. Wait for the Flask app to be ready, then curl
    - name: Test e2e
      run: |
        sleep 5
        docker ps -a
        docker logs mysql-db
        curl -f http://localhost:5000/
      