name: deliver-and-deploy
on:
  workflow_call:
jobs:
  deliver:
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
      contents: read

    steps:

    - name: Configure AWS Credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: arn:aws:iam::889867978066:role/github-actions-ecr-push-role
        aws-region: ap-south-1 
        disable-retry: true 

    - name: Checkout code
      uses: actions/checkout@v6

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Prepare for e2e test
      run: docker compose up -d
      env:
        DB_HOST: ${{ vars.DB_HOST }} 
        DB_USER: ${{ vars.DB_USER }}
        DB_NAME: ${{ vars.DB_NAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: entry-tracker
        IMAGE_TAG: latest

    - name: Execute integration test
      run: |
        chmod u+x $SCRIPT_PATH
        $SCRIPT_PATH
        docker compose down
      env:
        SCRIPT_PATH: ./.github/scripts/test_entry_tracker.sh
    # - name: Print next tag
    #   run: echo "${{ steps.resolve-tag.outputs.NEXT_TAG }}"

    # - name: Build, tag, and push image to Amazon ECR
    #   working-directory: ./entryTracker
    #   env:
    #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    #     ECR_REPOSITORY: entry-tracker
    #   run: |
    #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
    #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
    # - name: Run script on instance
    #   run: |
    #     echo "Sending deployment script to tagged EC2 instances"
        
    #     COMMAND_ID=$(aws ssm send-command \
    #       --document-name "AWS-RunShellScript" \
    #       --comment "Deploying entry-tracker:${{ github.sha }}" \
    #       --targets '[
    #         {"Key": "tag:Environment", "Values": ["staging"]},
    #         {"Key": "tag:Project", "Values": ["entry-tracker"]}
    #       ]' \
    #       --parameters 'commands=[
    #         "sudo -u ec2-user -i bash -c \"touch /home/ec2-user/hi-hi\""
    #         "printenv | grep 'DB_' > /home/ec2-user/env_vars.txt"
    #       ]' \
    #       --query "Command.CommandId" \
    #       --output text)
          
    #     echo "Command sent successfully. Command ID: $COMMAND_ID"





    # - name: Ship Docker Compose Manifest
    #   uses: ./.github/actions/ssm-ship-file
    #   with:
    #       source-file: './docker-compose.yaml'
    #       target-path: '/home/ec2-user/entry-tracker/docker-compose.yaml'
    #       environment-tag: 'staging'
    #       project-tag: 'entry-tracker'

















    # - name: Ship docker compose file via ssm to ec2 instance by tags
    #   env:
    #     # Load the target AWS Account ID or use static values
    #     AWS_ACCOUNT_ID: "889867978066"
    #     AWS_REGION: "ap-south-1"
    #   run: |
    #    BASE64_PAYLOAD=$(base64 -w 0 ./docker-compose.yaml)
          

    #     echo "Shipping compose layout to tagged EC2 instances..."

    #     # 2. Trigger SSM command using the clean variable
    #     COMMAND_ID=$(aws ssm send-command \
    #       --document-name "AWS-RunShellScript" \
    #       --comment "Deploying via Environment Variable Sync:${{ github.sha }}" \
    #       --targets '[
    #         {"Key": "tag:Environment", "Values": ["staging"]},
    #         {"Key": "tag:Project", "Values": ["entry-tracker"]}
    #       ]' \
    #       --parameters "{\"commands\": [
    #         \"echo $BASE64_PAYLOAD | base64 --decode > /home/ec2-user/docker-compose.yaml\"
    #       ]}" \
    #       --query "Command.CommandId" \
    #       --output text)
          
    #     echo "Sync complete. Tracking Command ID: $COMMAND_ID"