name: Reusable build and unit test workflow

on:
  workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./entryTracker
    steps:

    # 1. Check out the repository code
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7
    
    # 2. Set up Python 3.10
    - name: Set up Python 3.10
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 #v6.3.0
      with:
        python-version: '3.10'
        cache: 'pip' 
        cache-dependency-path: 'entryTracker/requirements.txt'

    - name: Initiate report artifact
      run: |
        cat << EOF > report.txt
        ============================================================
        [$(date)]install and unit test started
        ============================================================
        EOF
        
#==============================================================================================
#                                             install
#==============================================================================================
    - name: Install dependencies
      run: |

        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
        if [ $? -eq 0 ]; then
          echo "[$(date)]dependencies installed sccessfully" >> report.txt
        else
          echo "[$(date)]failed installing dependencies " >> report.txt
          exit 1 
        fi
        
#==============================================================================================
#                                             run
#==============================================================================================
    - name: Run App and Test with Curl
      run: |
        python app.py &
        if [ $? -eq 0 ]; then
          echo "[$(date)]app started in background" >> report.txt
        else
          echo "[$(date)]app failed to start" >> report.txt
          exit 1 
        fi
        

#==============================================================================================
#                                             unit test
#==============================================================================================
    - name: Unit test
      run: |
        sleep 3
        RESULT=$(curl -f http://127.0.0.1:5000/)
        if echo "$RESULT" | grep -q "current_entry"; then
          echo "[$(date)]uinit test success" >> report.txt
        else
          echo "[$(date)]unit test fail" >> report.txt
          echo "$RESULT" >> report.txt
          exit 1
        fi

        echo "result: $RESULT" >> report.txt
        echo pwd
        
    - name: Upload artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: report-artifact
        path: ./report.txt