name: package-and-e2e
on:
  workflow_call:
    secrets:
      DB_PASSWORD:
        required: true
      DB_ROOT_PASSWORD:
        required: true

jobs:
  integration-and-delivery:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write 

    steps:
    # 1. Check out the repository code
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7
    
      with:
        fetch-depth:
          0


#==============================================================================================
#                                             Package
#==============================================================================================
    - name: Package
      run: |
        docker compose up -d
      env:
        DB_HOST: ${{ vars.DB_HOST }} 
        DB_USER: ${{ vars.DB_USER }}
        DB_NAME: ${{ vars.DB_NAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
   
#==============================================================================================
#                                          Integration test
#==============================================================================================
    - name: Execute integration test
      run: |
        chmod u+x $SCRIPT_PATH
        $SCRIPT_PATH
        docker compose down
      env:
        SCRIPT_PATH: ./.github/scripts/test_entry_tracker.sh

#==============================================================================================
#                                          Resolve tag
#==============================================================================================
    - name: Resolve next tag
      id: resolve-tag
      uses: ./.github/actions/resolve-next-tag
      with:
        major-minor-patch: 'patch'


#==============================================================================================
#                                         configure AWS 
#==============================================================================================
    - name: Configure AWS Credentials via OIDC for ECR image push
      uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b #v6.2.0
      with:
        role-to-assume: arn:aws:iam::889867978066:role/gh-actions-ecr-push-role
        aws-region: ap-south-1 
        disable-retry: true 

#==============================================================================================
#                                         Login to ECR
#==============================================================================================
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

#==============================================================================================
#                                          Tag current commit
#==============================================================================================
    - name: Tag commit
      run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag $IMAGE_TAG 
          git push origin $IMAGE_TAG 
      env:
        IMAGE_TAG: ${{ steps.resolve-tag.outputs.NEXT_TAG }}

#==============================================================================================
#                                         Tag and push  to ECR
#==============================================================================================
    - name: Tag the entry tracker image
      run: |
        
        #tag images
        docker tag local/entry-tracker:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker tag local/entry-tracker:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
        
        #push images
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

        echo "New tag created: $$IMAGE_TAG
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: entry-tracker
        IMAGE_TAG: ${{ steps.resolve-tag.outputs.NEXT_TAG }}

