name: package-and-e2e
on:
  workflow_call:
    secrets:
      DB_PASSWORD:
        required: true
      DB_ROOT_PASSWORD:
        required: true

jobs:
  package-e2e:
    runs-on: ubuntu-latest
    steps:
    # 1. Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v6


    # - name: List images
    #   run: docker images  

    # 3. Spin up the containers (They will now successfully read the job-level Env vars)
    - name: Prepare for integration test
      run: |
        docker compose up -d
      env:
        DB_HOST: ${{ vars.DB_HOST }} 
        DB_USER: ${{ vars.DB_USER }}
        DB_NAME: ${{ vars.DB_NAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
   
    # 4. Wait for the Flask app to be ready, then curl
    - name: Execute integration test
      run: |
        chmod u+x $SCRIPT_PATH
        $SCRIPT_PATH
        docker images
        
      env:
        SCRIPT_PATH: ./.github/scripts/test_entry_tracker.sh
        